language: minimal
matrix:
  include:
  - env: ARCH=windows
  - env: ARCH=macos
  - env: ARCH=linux_x86_64
addons:
  apt:
    packages:
    - unzip
    - zip
install: skip
script: ./build.sh
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file:
    - output/*.tar.gz
    - output/*.zip
    - output/*.sha1
    - output/*.sha256
    - output/*.sha512
  file_glob: true
  skip_cleanup: true
  on:
    repo: drayde/fomu-toolchain
    all_branches: true
    tags: true
branches:
  only:
    # Release tags
    - /^test\d+/